DROP DATABASE IF EXISTS DOE;
CREATE DATABASE DOE;
USE DOE;

CREATE TABLE IF NOT EXISTS DOADOR(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(255),
EMAIL VARCHAR(255),
BLOOD VARCHAR(4),
PRIMARY KEY(ID));