DROP DATABASE IF EXISTS db_doesangue;
CREATE DATABASE db_doesangue;
USE db_doesangue;

CREATE TABLE IF NOT EXISTS doador(
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(255),
email VARCHAR(255),
tipo_sanguineo VARCHAR(4),
PRIMARY KEY(id));