version: "3.1"
services:
  db:
    image: mariadb
    volumes: 
        - "./mysql:/var/lib/mysql"
    ports: 
        - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db_doesangue

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    ports: 
        - "8081:80"